title: HPShelton
description: Programming, Privacy, Politics, Photography
author: H. Parker Shelton
url: https://hpshelton.com
feed:
  path: /feeds/atom.xml

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

markdown: CommonMarkGhPages
commonmark:
   extensions:
   - autolink
   options: ["UNSAFE"]

plugins:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  category:
    output: true

paginate: 10
paginate_path: "/page/:num/"

timezone: America/Los_Angeles
