defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

markdown: CommonMarkGhPages
commonmark:
   extensions:
   - autolink
   options: ["UNSAFE"]

plugins:
  ##- jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  category:
    output: true

paginate: 10
paginate_path: "/page/:num/"

timezone: America/Los_Angeles