name: publish-blog

on:
  schedule:
    - cron:  '0 1 * * *' # Runs every day at 1 AM UTC

jobs:
  publish:
    name: publish-blog
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages build
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $PAGES_TOKEN"
        env:
          PAGES_TOKEN: ${{ secrets.PAGES_TOKEN }}
